### ISSUE TITLE
Load Auth doesn't emit signal when logged in[BUG]

### ISSUE THREAD

**Issue by Zarasan** [GodotNuts/GodotFirebase#174]
**Describe the bug**
load_auth doesn't emit login_successful when completing login
**To Reproduce**
load auth

**Expected behavior**
It should give login_successful signal if its logged in?

**Screenshots**
![image](https://user-images.githubusercontent.com/43384612/114668946-a1340080-9d01-11eb-9f8f-b15ee27eb36f.png)
![image](https://user-images.githubusercontent.com/43384612/114668998-b0b34980-9d01-11eb-9d88-c8e884e5e9b6.png)

**Environment:**
 - OS: Windows 10

**Additional context**
I added new option 
`const RESPONSE_ASSERTION : String  = "identitytoolkit#VerifyAssertionResponse"`
and added it to the login successful signal when the request is completed

**Comment by BearDooks** [comment]
@Zarasan This should emit the signal of being logged in when you load_auth(). Might I suggest using the check auth file command instead. It has some logic built in to make sure the auth file exists before you try to load it. 

https://github.com/GodotNuts/GodotFirebase/wiki/Authentication-and-User-Management#check-encrypted-auth-file

In the meantime I will runs some local tests and get back to you.

~ Chuck

**Comment by Zarasan** [comment]
@BearDooks I check if the auth file exists, my question was after it loads the file I have no return information that the user is logged in.
load_auth() file loads the file and sends a request but the request handler doesn't match the password assert reply firebase sends back.

**Comment by BearDooks** [comment]
@Zarasan OK. Let me look into it. I know this worked before, but Google may have changed how things work. They tend to do this and break our stuff.

Thanks for the heads up.

**Comment by BearDooks** [comment]
@Zarasan I think I see what is going on. This is all assuming you are using load_auth() because you have saved the auth file local to the device.

When you check for the auth file, it will auto load it for you. This process involves calling a manual refresh of the token, similar to a normal refresh when the token expires. Looking through our code and my notes, this does not 'log a user in' since they are tech already logged in, we are just refreshing their token for them.

I just cloned the newest version and ran it through our automated tester. I am not seeing any errors, and the load_auth() function is working correctly for me.

Does this make sense?

**Comment by Zarasan** [comment]
Ok, sorry my mistake had a wrong idea about what load_auth does.

So I have a login screen right now and it checks for the auth file, if its there is does load_auth, how will I know that the auth is correct? Should I do load_auth then after a few seconds check if Firebase.Auth has valid localid?

**Comment by BearDooks** [comment]
@Zarasan No worries. Its really up to you how you want to handle it.

I always envisioned an app asking a user if they wanted to stay logged in with a checkbox, how you save that choice is up to you.

When a user wants to stay logged in, I would check for the auth file before you show them the login page, if it doesn't exist load the login page. If it does exist refresh the token. There should be some signals you can connect to to monitor if the token refresh worked or not. 

More than happy to work with you on that since you are the first person I know of who is trying to use this feature.

**Comment by Zarasan** [comment]
Hey, so I tinkered with my code and added:
`requesting = Requests.LOGIN_WITH_MANUAL_AUTH`
![image](https://user-images.githubusercontent.com/43384612/114866045-63afa000-9df3-11eb-8612-ab5e86a14fe8.png)

and
```
Requests.LOGIN_WITH_MANUAL_AUTH:
     emit_signal("login_succeeded", auth)
```
![image](https://user-images.githubusercontent.com/43384612/114866142-7de97e00-9df3-11eb-9e32-73034502de59.png)

**Comment by BearDooks** [comment]
@Zarasan glad that is working for you. I have been talking to the other team members, and we are not sure if that is something we are going to add to the plugin. 

The discussion boiled down to, if we did add it, we would probably use a different signal, since you are not technically logging in again, but rather just refreshing the previous session. In that sense, we already have a signal that fires off called 'token_exchanged', which you might be able to look for in your code if you really needed to make sure someone had the correct auth file to use the APIs.

We also threw around the idea of having a function for checking if someone was logged in our not, but there is always a small margin for error when dealing with a timed token, so we can't always rely on it to work 100% of the time.

Reading back through this thread, you will know if the the loading of the file works, because if we can't refresh the token, we threw an error in the plugin, since Firebase would send some sort of error back to us. 

Hope this helps and makes things somewhat more clear. 

Chuck

**Comment by Zarasan** [comment]
Thanks for the help, I'll close this now as it is not a bug and it is figured out.
