### ISSUE TITLE
[BUG] Firestore query does not seem to use auth properly

### ISSUE THREAD

**Issue by ReneHabermann** [GodotNuts/GodotFirebase#182]
**Describe the bug**
I'm trying to access a firestore collection by query. The collection has read permissions (which includes list) for anyone that is authenticated. I can get single documents, but the queries fail with 403.

**To Reproduce**
Set up a collection "names" with 
```
 match /names/{document} {
      allow read: if request.auth != null;
    }
```

Then register with mail and login, after which you should be authenticated. Then try to access the documents by query. I used this
```
	var query:FirestoreQuery = FirestoreQuery.new().from("names").where("name", FirestoreQuery.OPERATOR.EQUAL, n).limit(1)
	var query_task:FirestoreTask = Firebase.Firestore.query(query)
	var result = yield(query_task, "task_finished") #btw, in the wiki example this is typed as array, which does not work in this error case (dictionary is returned). There are many problems like this throughout the code, that arise from a method returning different types
	print(result)
	
	var collection : FirestoreCollection = Firebase.Firestore.collection("names")
	var document_task : FirestoreTask = collection.get("wVgOp7JWuQcnPkS1G7hh")
	var document : FirestoreDocument = yield(document_task, "get_document")
	print(document)
```

prints
{code:403, message:Missing or insufficient permissions., status:PERMISSION_DENIED}
doc_name: wVgOp7JWuQcnPkS1G7hh, 
doc_fields: {name:Bert}, 
create_time: 2021-04-18T21:12:50.789961

**Expected behavior**
Query is returned, delivering all matches.

**Environment:**
 - Windows 10
 - GodotFirebase Code from today 20:00 CEST

**Comment by WolfgangSenff** [comment]
Not sure if this is actually needed, but try adding this to your rules:
`service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth != null;
    }
  }
}`

Obviously you'll need to change it around so it's matching the structure you want, but this one works pretty well for us. Let me know if it does for you.

**Comment by WolfgangSenff** [comment]
Oof, that did not format well. Sorry. Hopefully it can work anyway.

**Comment by fenix-hub** [comment]
Both this and your other issue #181 seems related to permission errors, which may not depend by our plugin but eventually by your project configuration.
But to confirm that and investigate we would need to have a reproduction for your case, since we can only state that the things work using our permissions on our own projects.
Try changing permissions for your project as @WolfgangSenff suggested, anyway we can do some tests by our side. But in our environment (and probably in other users' enviroments) there is no issue related to our requests.
Let us know!

**Comment by ReneHabermann** [comment]
Thank you for your replies! Indeed @WolfgangSenff permission worked, which sent me down an investigation.
Basically, i allowed read access on a collection (when authenticated), where Wolfgang allowed basically anything to a authenticated user. This is too broad for me, and probably for most use cases, so i couldn't stick with it.
The issue was, that the "from" part in the FirestoreQuery by default also queries sub-collections, for which a broader permission is required. When i changed the request to not include sub-collections, it worked.

So, there is no bug, just the documentation could use a little update. It states
> Note you need to be authenticated for this to work

Which is, from what i understand, neither correct for this case nor for firebase in general. You should be able to access via query even when not authenticated, it's just the firebase rule has to match. Like
```
service cloud.firestore {
  match /databases/{database}/documents {
    match /user_list/{document} {
      allow list: if true;
    }
  }
}
```
(when not querying sub collections).

**Comment by handre-dev** [comment]
Similar issue here, but none of the above solutions worked for me.
I have the exact same rule structure, every other read request work fine but queries. I keep getting 403.
My rules:
```
service cloud.firestore {
  match /databases/{database}/documents {
    match /my_list/{document} {
      allow list: if true;
    }
  }
}
```
My query:
```
var result : Array = yield(Firebase.Firestore.query(FirestoreQuery.new().from("my_list")), "result_query")
```

Also, I think I found a bug in firestore_task.gd: when returning errors (lines 158 and 164), the variable 'bod' is treated like a dictionary and asked for keys().size(), but there are no keys since bod is an array at that point, and it crashes the function. Solved removing the keys() call.
