### ISSUE TITLE
[FEATURE REQUEST] Oauth automatic redirect

### ISSUE THREAD

**Issue by LoneDespair** [GodotNuts/GodotFirebase#203]
**Is your feature request related to a problem? Please describe.**
The user would have to copy and paste a code from their browser back to the app, which is a minor inconvenience but feels very odd

**Describe the solution you'd like**
A way to automatically redirect users back to the app after selecting an account, and without having to copy paste the code/token

**Describe alternatives you've considered**

**Additional context**

**Comment by fenix-hub** [comment]
Hi @LoneDespair !
I'm the guy behind the OAuth implementation. I'd really like to support this feature, since I prefer it among the manual copy-paste.
The thing is that such feature requres some testing that currently I'm unable to do.
I know that the minimum requirements for such thing to work is to
1) have a redirect URI (a domain you have control over) to handle the data
2) the application needs to listen to that URI
Honestly I don't know if that is entirely possible without having subviews (since Godot doesn't support them currently) and without using the SDK.
But since you are asking for this, and I think it is something other people would like to have, I can investigate further.
Do you have any useful resource for this?

**Comment by LoneDespair** [comment]
Greetings! @fenix-hub

My gratitude for oauth implementation and for sharing some information which would be handy in the future

Sadly I lack expertise on this area, to distinguish if any resource I saw would be of any use

**Comment by fenix-hub** [comment]
No problem. I'll se what I can get with the desktop (windows, linux, macOS) support of this feature, since it seems the feasible

**Comment by fenix-hub** [comment]
Hi @LoneDespair ,
I've mentioned this issue in a PR implementing this feature for desktops.
You can test it calling the `get_google_auth_localhost()` function.

**Comment by LoneDespair** [comment]
> Hi @LoneDespair ,
> I've mentioned this issue in a PR implementing this feature for desktops.
> You can test it calling the `get_google_auth_localhost()` function.

Tysm! wasn't expecting to be implemented so fast

Is now using this feature on a project
