### ISSUE TITLE
[BUG] Unable to update document with field that begins with number

### ISSUE THREAD

**Issue by macktns** [GodotNuts/GodotFirebase#211]
**Describe the bug**
Requesting an udpate with a field that begins with a number such as "22" or a combination like "2difj523ji" returns with an "invalid property path". Changing the same update to be a field that begins with a letter allows the update to go through. 

**To Reproduce**
This is a basic update to a collection on the main current version. 
collection.update(online_level_id, {"22":"1"}) does not work. 
collection.update(online_level_id, {"uu":"1"}) does work.  

**Environment:**
 - OS: Windows 10
 - Browser chrome
This is useful because document id's often begin with numbers and I would like to store them as field's in other documents.
Sorry for the two reports, trying hard to get this working.

**Comment by WolfgangSenff** [comment]
https://firebase.google.com/docs/firestore/quotas#limits

Extremely weird, but see the Collections, Documents, Fields header, down at the 4th one from the bottom, Constraints on field paths. The last one of those clearly makes it so you can't start it with a number.

I'm going to go ahead and close this since there's nothing we can do about it, but in the future, I may see about implementing field path validation to ensure people find that link to it, so thanks! (Don't hesitate to open up multiple issues when you need to.)

**Comment by macktns** [comment]
Ah thank you very much. It's very odd they let you manually put fields in that start with a number, that's why I assumed this was a bug either with Godot or the plugin.

**Comment by WolfgangSenff** [comment]
My first instinct was the same of course! There appears no real reason they must do that, but it must be some weird bug they themselves have had to work around, so just said to not do it. :P
