### ISSUE TITLE
[FEATURE REQUEST] Any updates on snapshots? listeners?

### ISSUE THREAD

**Issue by shafnaz** [GodotNuts/GodotFirebase#263]
Hello contributors,
Great work with the plugin!
Are there any news updates, plans for listeners or snapshots? That's a great feature to have for multiplayer games, real-time and turn-based multiplayer games. Can't seem to find alternatives because this plugin makes programming less work, especially if you don't know a lot about security.

**Comment by WolfgangSenff** [comment]
We already support listeners/snapshots for the real-time database. :) They're just implemented as signals, because that's how Godot does it! You can't really effectively use this plugin (or any REST-based Firebase plugin) for anything super real-time though - be careful with that. I know, I know, it says real-time in the name, but it is most definitely not even close, and it is very expensive to try to use it in that fashion.

As for updates, we are slowly updating it over time and fixing bugs. Listeners/snapshots for other features are not implemented because they do not have a REST interface generally - most are only supplied by gRPC, which neither we nor Godot itself supports in GDScript. Does that answer your questions? Feel free to ask more if you want.

**Comment by shafnaz** [comment]
Alright I'll check it out. I hope better support comes out for real-time games

**Comment by WolfgangSenff** [comment]
It won't. :/ I talked to the team about it, they are not focusing on that. They're focusing on speeding it up for sure, but they say that at least the REST-based API (which is all we can rely on for this in GDScript) can only ever be somewhat slow. They've tested it pretty exhaustively, because the REST API is used in a ton of other game engines as well, and it doesn't work really in any of them. I'm going to go ahead and close this - let me know if you have any other questions though. We're more likely to answer faster on Discord!
