### ISSUE TITLE
[FEATURE REQUEST] Is Realtime Database really slow as this example?

### ISSUE THREAD

**Issue by shafnaz** [GodotNuts/GodotFirebase#272]
Hello developers,

I'm working on a project and want to know if this behavior is expected. This is a demo of the gameplay.
Each time the player makes a move, an `update(path : String, data : Dictionary)` is called.
My Download: 6.28 Mbps
My Upload: 3.07 Mbps

You guys mentioned it's because of the REST API which is the only supported option at the moment.
I guess I will have to make my game turn-based.

Data I send looks like this :
![image](https://user-images.githubusercontent.com/37254287/143262927-ad2e4d94-d575-4b0d-a177-749b96953ca5.png)

![issue](https://user-images.githubusercontent.com/37254287/143261777-0226aa7f-88fb-4825-a951-82b051eaa749.gif)

**Comment by WolfgangSenff** [comment]
Yes - even non-REST-based Firebase APIs are not fast enough to do what you're suggesting. On top of that, doing what you're suggesting will cost a *lot* of money. The Firebase team has explicitly said that they will never be able to support true real-time functionality needed for gaming. Closing this because we cannot change that.
