### ISSUE TITLE
[FEATURE REQUEST] Implementation of transactions for Firestore

### ISSUE THREAD

**Issue by iRedFox** [GodotNuts/GodotFirebase#291]
**Is your feature request related to a problem? Please describe.**
Its hard to sync data between all players. As an example, if three players are contributing to a global field value on the database. If all them did update on the same time, there will be desyncronization.

**Describe the solution you'd like**
Transcations for Firestore

**Describe alternatives you've considered**
Realtime database

**Additional context**

**Comment by WolfgangSenff** [comment]
Unfortunately we cannot do that - snapshots in that sense require a gRPC implementation that we can't provide. Transactions are different. They are where you open a transaction, commit some changes, and submit it all in one "action". This feature is for transactions, not for snapshot syncing. This will make it so multiple updates sent at the same time won't desync your data, which is what your original complaint was. If that's not what you intended, we can either close this or leave it, since people do want transactions.

**Comment by WolfgangSenff** [comment]
I have figured out how to manage the above! In addition, it might bring something else that is very cool, just have to figure out how to do it in entirety. :) In any case, just updating you that soon, you'll be able to do transactions! As I'm reworking the entire Firestore part of the plugin, it might be a hot minute until I've finished it, but very happy with how it works with other things that are considered to be transactions already. Those are already in the codebase in the latest 4.x version, so feel free to check it out!

**Comment by WolfgangSenff** [comment]
I have implemented commits finally for Godot! While it's not exactly this, it does allow for exactly what the original post wanted! So I'm going to close this for now. See my latest release and the new [Firestore Guide](https://github.com/GodotNuts/GodotFirebase/wiki/Upgrade-Guide-to-4.x-version-2) for more!
