### ISSUE TITLE
[BUG] Calling _on_error with 4 arguments

### ISSUE THREAD

**Issue by handre-dev** [GodotNuts/GodotFirebase#294]
I'm using latest version

When trying to get a document after authentication I get an error 404 but the error printing breaks and return the following message.

E 0:00:02.499   emit_signal: Error calling method from signal 'task_error': 'Reference(firestore_collection.gd)::_on_error': Method expected 3 arguments, but called with 4..
  <C++ Source>  core/object.cpp:1236 @ emit_signal()
  <Stack Trace> firestore_task.gd:170 @ emit_error()
                firestore_task.gd:155 @ _on_request_completed()
                firestore.gd:305 @ _pooled_request()
                firestore_collection.gd:120 @ _process_request()
                firestore_collection.gd:46 @ get()
                auth.gd:403 @ _on_FirebaseAuth_request_completed()

**Comment by BearDooks** [comment]
@OvervaultDev Sorry I just noticed there are some issues that need to be looked at. Is this still a problem? If so can you share some of the code that is causing the error?

**Comment by OvervaultDev** [comment]
@BearDooks I should have attached a snipped before, I've changed my script a lot of times since then.
Sorry for that!

**Comment by BearDooks** [comment]
@OvervaultDev no worries, is it still an issue?

**Comment by WolfgangSenff** [comment]
@handre-dev - can you show us what you have connected to the firestore_task task_error signal? The method you've done that with has only three arguments to it but needs four. This was an update to help clarify what the plugin was trying to do when the errors occurred, which was lost to the winds before. I'll close this now since it's been a long time since we heard back, feel free to reopen if you need to.
