### ISSUE TITLE
Getting "Null" When calling get_user_data()

### ISSUE THREAD

**Issue by Rikoo132** [GodotNuts/GodotFirebase#329]
**Describe the bug**
When I call get_user_data() and print it, it prints null even the user is logged in.

Code I used :
func _on_FirebaseAuth_login_succeeded(auth):
	var user = Firebase.Auth.get_user_data()
	print(user)

**Comment by WolfgangSenff** [comment]
Yes, that's expected. You're getting null because it's a void return. https://github.com/GodotNuts/GodotFirebase/blob/c2b6a0952fe57c1e1de23e47dcb59344b64a1c23/addons/godot-firebase/auth/auth.gd#L530

What you need to do is connect to the userdata_received signal, found here: https://github.com/GodotNuts/GodotFirebase/blob/c2b6a0952fe57c1e1de23e47dcb59344b64a1c23/addons/godot-firebase/auth/auth.gd#L22

In addition to this, when you receive the auth variable in your handler the way you have it, that is already the user data, so you can just look at it there.
