### ISSUE TITLE
Add full documentation

### ISSUE THREAD

**Issue by JekSun97** [GodotNuts/GodotFirebase#356]
I recently came across your wonderful plugin, but according to the documentation I could only register myself in the firebase database, it’s not clear how to work with other aspects of the plugin, the database, how to load something from there, how to read it, or how to work with the database in real time for example for a mini social network.

Please complete the documentation on all aspects, thank you!

**Comment by WolfgangSenff** [comment]
Have you seen our wiki? We also have a ton of demos in the parent github company showing how to make an Instagram clone, one for a chat program, and others. The wiki is pretty solid, and if needed, you can look at our tester program that we use to test people's integrations (and ours). And if there's stuff missing, try to be a little more specific after you read the wiki!

Here's just an example of the wiki: https://github.com/GodotNuts/GodotFirebase/wiki/Realtime-Database

And here's the Insta clone: https://github.com/GodotNuts/FirebaseDemo-SociaDot

I'm closing this because I find it to be vague and think you may have just missed the wiki; feel free to reopen if you have more specific comments!

**Comment by JekSun97** [comment]
Sorry, I'm new to Github )
Thanks for the answer!
