### ISSUE TITLE
parse: Error parsing JSON at line 2: Expected 'EOF'

### ISSUE THREAD

**Issue by EmineBS** [GodotNuts/GodotFirebase#383]
I'm getting this error several times, are there problems with the data I'm sending?

**Comment by WolfgangSenff** [comment]
I have no idea, since you haven't posted the code or anything relevant to your issue aside from the most minimum number of words. Can you try to explain your issue clearly, with an example of the code you're using, and a screenshot of where the error is happening and stuff? That would help us to understand it better, hopefully.

**Comment by WolfgangSenff** [comment]
I'm going to go ahead and close this. You can open it again if you feel like you need to, but no response means we cannot help at this time.
