### ISSUE TITLE
[FEATURE REQUEST] read only when something changed 

### ISSUE THREAD

**Issue by QonDonion** [GodotNuts/GodotFirebase#385]
**Is your feature request related to a problem? Please describe.**
well i'm testing the webRTC and needed to store the Offer somewhere and i chose the fireStore database, but i only want to read the database only when an Answer is added to the database

**Describe the solution you'd like**
i want like the onSnapshot() function [https://firebase.google.com/docs/firestore/query-data/listen](https://firebase.google.com/docs/firestore/query-data/listen) it does the cool thing!!

**Describe alternatives you've considered**
there's this signal called 'update_document' in 'FirestoreCollection' but it only fires when the game updates the database and not when the database updated

**Additional context**
![Screenshot_259](https://github.com/GodotNuts/GodotFirebase/assets/97073859/4638be06-e451-441e-85bf-5ef5ff167638)
![Screenshot_258](https://github.com/GodotNuts/GodotFirebase/assets/97073859/0ef3d85b-f49a-4bfc-a118-34374c1d0bf5)
yeah

**Comment by WolfgangSenff** [comment]
Unfortunately, we cannot do such a thing! I wish we could as well. That doesn't exist via the REST API, otherwise it would definitely have been implemented ages ago. I'd handle that either by making a Cloud Function that listens for changes to them and puts a change into the realtime database (which does support it), or just use the realtime database directly. I'm going to go ahead and close this as it's not possible for us to implement it. For more, see the list of possible methods that we can/have implemented here: https://firebase.google.com/docs/firestore/reference/rest/
