### ISSUE TITLE
[BUG] Latest addon on 4.x branch doesn not work for Godot 4.2.2

### ISSUE THREAD

**Issue by altamkp** [GodotNuts/GodotFirebase#394]
**Describe the bug**
I have cloned the repository and switched to the 4.x branch, then copy the folders in `addons` to a newly created project. Upon opening the project, errors pop up showing that compilation has failed.

**To Reproduce**
1. Create a new Godot project
2. Clone this repo
3. Switch to 4.x branch
4. Copy contents in the `addons` directory the to root of the Godot project
5. Open project in Godot Editor

**Expected behavior**
Addon scripts should compile correctly

**Screenshots**
![image](https://github.com/GodotNuts/GodotFirebase/assets/65537185/9fed2bf7-f5e1-4993-bf86-47f62dad9d87)

**Environment:**
- Godot: 4.2.2
- OS: Windows 10

**Additional context**
I am aware of this reference here #https://github.com/GodotNuts/GodotFirebase/issues/375 and have tried delete the `.godot` folder, but it didn't help.

**Comment by WolfgangSenff** [comment]
For the sake of argument, go here and download the 4.x branch of this: https://github.com/GodotNuts/GodotFirebaseTestHarness/tree/4.x

I have placed it on the 4.x branch for your convenience. Try running it - it just has to compile. If that works, then this isn't a bug with our system but instead your own setup. I suspect you're inadvertently still on 3.x, or that you just have some stuff dangling around from having not closed Godot when deleting the .godot project, but obviously I can't know since you didn't really post that much info about it. 

In general, it's better to get the addon from the asset library, as it will be integrated properly there. It's entirely possible it will still cause problems with the .godot folder, but it is less likely that you clone 3.x and have a problem from that at first, because it controls that and just gets 4.x immediately. Let me know how the Test Harness above goes. You don't even have to put in your own .env file because it should just compile and work - it won't give you any results, but it won't fail to compile, either.

**Comment by WolfgangSenff** [comment]
I'm going to go ahead and close this, since I haven't heard back for over a month.
