### ISSUE TITLE
[BUG] Firebase Storage: A StorageRefrence is valid even though the file it refrences does not exist.

### ISSUE THREAD

**Issue by ronsiv8** [GodotNuts/GodotFirebase#395]
**Describe the bug**
When getting a storagerefrence to a file, in my program that file can sometimes not exist. The boolean valid in StorageRefrence is perfect for this, however, when using it, it seems that the file that doesnt exist is still valid.

**To Reproduce**
Attempt to get a reference of a nonexistant file. Check the valid boolean value.

**Expected behavior**
The boolean value is true. Additionally, when trying to load the file, the firebase script runs into the following error:
Invalid get index 'downloadTokens' (on base: 'Dictionary'). -> on line 195 of the FirebaseStorage script.

**Environment:**
 - OS: Android and windows 11, but other platforms most likely also applicable.
 - Browser: didnt test it, but most probably applicable.

**Comment by WolfgangSenff** [comment]
Hm. Very weird. I'll have to look into this. I'm not sure we can do anything about the first bug - unless it has tried to get the file, the Godot code can't know whether or not it exists in Firebase. But maybe there's something, not sure, like an "exists" function.

**Comment by ronsiv8** [comment]
I'd really appreciate it. As of now, I came up with a scuffed-as-all-hell solution, but it is nothing im happy with, thats for sure.

**Comment by WolfgangSenff** [comment]
What happens when you try to just get the metadata?

**Comment by ronsiv8** [comment]
I'm gonna have to get back to you on that one tomorrow, i've got to head out now

**Comment by WolfgangSenff** [comment]
Been looking around, seems like there is no way to solve that problem. Our own valid property is used for after a file is deleted, nothing more. Apparently what you'd have to do is call list, then manually look for the file client-side.

How I've handled such a thing before is to make a Firestore reference document that holds onto metadata (in the traditional sense, rather than what Firebase Storage says is metadata). Then I can just ask to see if the document exists and if not, then don't attempt to get it. It's ugly, but doable.

**Comment by ronsiv8** [comment]
The project im working on has a server with the firebase admin api. I think ill just use that to check if images exist and share around download links. Its pretty odd that no exists function... Uhh, exists.

**Comment by WolfgangSenff** [comment]
I completely agree! I'll see if I can ask the Firebase team to add it.
