### ISSUE TITLE
OAuth Client ID credentials must be whitelisted in Firebase to work - add note to wiki

### ISSUE THREAD

**Issue by tommasodargenio** [GodotNuts/GodotFirebase#68]
No sure if that's just me but when I tried to use the OAuth workflow it didn't work at the beginning and I was getting the following error:

```
error code: 400
message: INVALID_IDP_RESPONSE : Invalid Idp Response: the Google id_token is not allowed to be used with this application. Its audience (OAuth 2.0 client ID) is xxxxxxxxxxxx.apps.googleusercontent.com, which is not authorized to be used in the project with project_number: yyyyyyyyyyyy

```

where xxxxxxxxx.apps.etc. it's the client ID I've created in the google console, while yyyyyyy is the project ID in Firebase.

To make it work I've added the google console client ID in the Whitelist for the google sign-in method in Firebase (there is an optional section called "Whitelist client IDs from external projects (optional)".

I thought I should mention this, perhaps it's worth adding this explanation in the Wiki

**Comment by fenix-hub** [comment]
Maybe I need some more info about this.

Did you enable Google sign-method?
What code did you use so I could replicate the same thing in a new project?

**Comment by tommasodargenio** [comment]
I followed the installation/activation instructions in the wiki to the letter. I've created a project in google console, and I've created an OAuth 2.0 credential using the desktop type, this has generated the web secret and the client ID. I've added this to the override.cfg as per instructions. 

in Godot then I use the same code listed in the instructions: 
Firebase.Auth.get_google_auth() to fire up the browser consent screen
and then Firebase.Auth.login_with_oauth(token.text) passing the token that I've got from the consent screen.

Since my Firebase account doesn't know anything about the google client ID I've created earlier, gives that [IDP error](https://imgur.com/lOcMFZ4).

Once I've added the google client ID in the Firebase [whitelist](https://imgur.com/OwXjNpA), within the Google Sign-in settings it all worked fine.

I've also found that I needed to connect my script to the token_exchanged signal so that I can capture the access and refresh token otherwise these get overwritten in the second phase of the authentication workflow. Having this tokens is very important as after logging in, I would need to use some other Google APIs calls and I wouldn't be able to do that without the access token.

**Comment by fenix-hub** [comment]
Hi @tommasodargenio ,

Looks like the IDP error happens if you create credentials for a project **different from the one you are using**.
I've got two Firebase projects:
- RistoranteDigitaleTest
- My First Project

I setup my Godot project using *RistoranteDigitaleTest*'s keys from Firebase.
I create OAuth keys using *My First Project* from Google Cloud Platform, and set clientId and clientSecret for the same Godot project.

Requesting OAuth authentication from my project, a google user will be authenticated using the *My First Project* oauth credentials on *RistoranteDigitaleTest*, which are keys still recognized as OAuth 2.0 but are not accepted for *RistoranteDigitaleTest* (since they were created for *My First Project*).

Now, I don't know what are your specific needings, but *if you have more than one Firebase project* **always** make sure to create your credentials for the same project you are using on Firebase.
![coD0rnG2hN](https://user-images.githubusercontent.com/45271396/105609599-ba847b00-5daa-11eb-8fb3-904eba4b142d.png)
![G8yf6kKz6O](https://user-images.githubusercontent.com/45271396/105609600-bbb5a800-5daa-11eb-902f-49ca848cbc43.png)
![ed53Wd8rNS](https://user-images.githubusercontent.com/45271396/105609664-16e79a80-5dab-11eb-9719-96c8b5a8377b.png)

Regarding tokens, here's a screen of the token request's response body 
![tQpQK0pB6c](https://user-images.githubusercontent.com/45271396/105610344-a000d080-5daf-11eb-82ee-285eecb40b03.png)
All tokens are correctly returned, even after the first `token_exchanged` signal.
This is the message returned both after a first authorization, and when the user is already authorized and stored in the Firebase project.
This body is returned by the `login_succeeded` signal as a Dictionary, but you can always get it in the end of the process with `Firebase.Auth.auth`.

Honestly I don't know why they disappear from the latest call. It could be linked to the error you are getting in the first place, which should be fixed with the first answer I gave you.
Both a print of `Firebase.Auth.auth` after the `token_exchanged` and `login_succeeded` signal (with all fields censored) would be very useful, but I think that resolving the first problem should also resolve this.

I'll leave this issue opened so we can discuss further about this. Let me know what you can get and I'll help you the best I can.

**Comment by BearDooks** [comment]
@tommasodargenio 

Just checking in to see if you got this working or if you need more help. 

Thanks

**Comment by tommasodargenio** [comment]
Thanks for the extensive explanation. I had it working by the way I've explained. I guess when you saying that the OAuth credentials in GCP must be for the same project, you mean the project in GCP must have the same name as the one in Firebase as otherwise, I can't see a connection between the two platforms (i.e. I can't see my Firebase project in the GCP developer console).

either way, it works so I'm happy to close this now.
