### ISSUE TITLE
Source code using double tabs instead of single tabs!

### ISSUE THREAD

**Issue by SIsilicon** [GodotNuts/GodotFirebase#85]
Firstly, thank you for this plugin! It is proving to be very useful in a game I'm working on. I'm even considering to contribute to the storage api.
Something is bothering me about the source code though. all the tabs seemed to have doubled. Where there would be one tab, there's two. Where there'd be two tabs, there's four. This does not adhere to the [gdscript style guide in the docs](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#indentation), and also wastes valuable scripting space.

If you'd like, I can do make a pull request with the changes.

**Comment by WolfgangSenff** [comment]
I'm attempting to normalize 4 spaces (rather than 2 tabs) with the team, but we'll fix it, since it's our weird bug that there's two tabs. :P 

As for storage, it seems a tricky bit since there's no built-in REST API through Firebase - it exists through GCP, but not Firebase itself. I'd accept a proposal if you were interested in providing one. I am not going to close this until we have fixed the tabs issue in either case, so you can feel free to drop your idea(s) here if you wanted to.

Finally, thanks! We appreciate any support at all. When I started on it way back long ago, I wasn't sure if anyone else was using it at all, but the folks that have contacted me in the meantime have joined a team, and we have big plans ahead. Look for a post on itch.io soon - I'll tag it with GodotFirebase there so it's easier to find (coming today - basically as soon as I'm done writing it).

**Comment by WolfgangSenff** [comment]
I have gone ahead and resolved this.
